### ISSUE TITLE
submit to CRAN?

### ISSUE THREAD

**Issue by gergness** [gergness/srvyr#10]
I'm thinking of submitting to CRAN in early January - 

Remaining todos:
1. ~~Create a single entry point for `design_survey()`, `design_survey_rep()` and `design_twophase()` (Re: #5)~~
2. Rework the vignettes to include new functions, and make them a little bit more differentiated from each other.
3. ~~Get code linted to a standard code style.~~
4. Go through all documentation.
5. Read through the R package manual and Hadley's book to make sure everything is in order.

What do you think @carlganz ? Any other things? Are you still planning on submitting a proposal about surveyRcpp?

**Comment by carlganz** [comment]
Hey,
This definitely seems worthy of submission to CRAN. I would also consider submitting an abstract for [UseR 2016](http://user2016.org/) if that is something that interests you. 

Truthfully, I don't think I will have the time to make`surveyRcpp` worthy of any sort of funding, so at the moment I have no plans for submitting a proposal, but it is still a long term goal (maybe summer 2017). I plan on working on `surveyRcpp` over Christmas break so we'll see.

Feel free to discard the vignette I added. It was mostly an exercise for me to use `sryvr` and for me to familiarize myself with pull requests. 

Kind Regards

**Comment by gergness** [comment]
Cool, thanks for the encouragement! Think you'll be going to UseR?
