### ISSUE TITLE
Error of mismatching argument lengths - "Argument 2 must be length 2, not 4"

### ISSUE THREAD

**Issue by stefanjwojcik** [gergness/srvyr#100]
I'm running into an error when I use any empty survey_total() command. In the examples for `survey_total()`, I run the following:

```
library(survey)
data(api)

dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw)

dstrata %>%
  group_by(awards) %>%
  summarise(pct = survey_total())

```
I get the following error: 

`Error: Argument 2 must be length 2, not 4`

I am getting the same error in production code that used to work. I have been unable to find any reason for this. Anybody know?

I'm on R 4.0.0 and srvyr version 0.4.0, but I get it on earlier versions too.

**Comment by gergness** [comment]
What version of dplyr do you have? 

I can't replicate with R 4.0.2, srvyr 0.4.0 and dplyr 1.0.2

**Comment by stefanjwojcik** [comment]
I'm on dplyr_0.8.5, but after some futzing I restarted R and the error disappeared. I have no idea wtf caused it, so I'll close this issue for now. Thanks so much for the rapid reply.
