### ISSUE TITLE
survey_ratio produces error when using group_by for a calibrated survey where one or more groups contains only NA values

### ISSUE THREAD

**Issue by dankshan** [gergness/srvyr#105]
Hello again could you please have a look at this? I feel like this is a new error as I think I used to be able to do this but I've tested with previous versions of srvyr as far back as 0.3.6 which all produce the same error. I've not tested with previous versions of dplyr.

I'm getting an error using survey_ratio and group_by where one of the groups does not have any data for the variable I'm trying to calculate a ratio from.

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': NA/NaN/Inf in foreign function call (arg 5)
```

This is only when using a calibrated dataset so the error may be by design?

Here is an example of where I'm struggling and would appreciate your help please. I've created a new variable called pcttest2 which is NA if cname == "Orange". Using pcttest2 in survey_ratio fails when grouping by cname.

```
library(survey)
library(srvyr)
library(dplyr)

#create a calibrated survey design using survey package example
data(api)

#create a new variable with NA values for "Orange" cname
apiclus1 <-
  apiclus1 %>%
  mutate(pcttest2 = if_else(cname == "Orange", NA_integer_, pcttest))

dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
pop.totals<-c(`(Intercept)`=6194, stypeH=755, stypeM=1018)
dclus1g3c <- calibrate(dclus1, ~stype+api99, c(pop.totals, api99=3914069), calfun="raking")

#create a srvyr survey object for the non-calibrated survey
dclus1_survey <- as_survey(dclus1)

#This works and shows NaN for the Orange group
dclus1_survey %>%
  group_by(cname) %>%
  summarise(pcttest2_pct = survey_ratio(pcttest2 == 100, !is.na(pcttest2), na.rm = TRUE, vartype = NULL))

#create a srvyr object for the calibrated survey
dclus1g3c_survey <- as_survey(dclus1g3c)

#This fails
dclus1g3c_survey %>%
  group_by(cname) %>%
  summarise(pcttest2_pct = survey_ratio(pcttest2 == 100, !is.na(pcttest2), na.rm = TRUE, vartype = NULL))
```

**Comment by gergness** [comment]
Hi, this is an error from the underlying `survey` package. 

```
survey::svyby(~pcttest2 == 100, ~cname, denominator = ~!is.na(pcttest2), svyratio, design = dclus1g3c_survey)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': NA/NaN/Inf in foreign function call (arg 5)
```

I'm not familiar enough with what you're trying to do to help you. My best guess is that you are specifying the denominator incorrectly, because `!is.na(pcttest2)` is something that can be 0, which would mean your denominator was 0, which could cause problems.
