### ISSUE TITLE
unweighted(mean(...)) in docstring

### ISSUE THREAD

**Issue by nalimilan** [gergness/srvyr#108]
The docstring for `unweighted` contains an example using `unweighted(mean(api99))`. I don't understand what it is supposed to show, as `mean(api99)` is enough to get the unweighted mean. Is this intended?
```R
library(survey)
library(dplyr)
data(api)

dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw)

dstrata %>%
  summarise(api99_unw = unweighted(mean(api99)),
            n = unweighted(n()))
```

**Comment by gergness** [comment]
Hm, yeah, the documentation was written at a time when `mean` didn't work outside of `unweighted`, I'm actually not sure when that changed. 

However, I do recommend using `unweighted` because in some circumstances, the `survey` package doesn't drop observations when filtering, but rather sets the weight to 0. The `unweighted` function takes care of this for you. We should add to the documentation to mention this.


See issue #51 and related for more discussion.

``` r
suppressPackageStartupMessages({
    library(survey)
    library(srvyr)
})
data(api)


# Declare basic clustered design ----
cluster_design <- as_survey_design(
    .data = apiclus1,
    id = dnum,
    weights = pw,
    fpc = fpc
)

# Add raking weights for school type ----
pop.types <- data.frame(stype=c("E","H","M"), Freq=c(4421,755,1018))
pop.schwide <- data.frame(sch.wide=c("No","Yes"), Freq=c(1072,5122))

raked_design <- rake(
    cluster_design,
    sample.margins = list(~stype,~sch.wide),
    population.margins = list(pop.types, pop.schwide)
)

raked_design %>% 
    filter(cname != "Alameda") %>% 
    group_by(cname) %>% 
    summarize(
        direct_unw_mean = mean(api99),
        wrapped_unw_mean = unweighted(mean(api99))
    ) %>% 
    filter(cname == "Alameda")
#> # A tibble: 1 x 3
#>   cname   direct_unw_mean wrapped_unw_mean
#>   <chr>             <dbl>            <dbl>
#> 1 Alameda             609              NaN
```

**Comment by nalimilan** [comment]
Thanks! The new explanations about zero weights are very useful. I even wonder whether it would make sense to required using `unweighted` explicitly to use functions other than those provided by srvyr as it's very easy to shoot oneself in the foot if you didn't realize subsetting merely marked some weights as zero.
