### ISSUE TITLE
Create `svy_stat` object

### ISSUE THREAD

**Issue by carlganz** [gergness/srvyr#11]
Here is something I've been working on. Let me know what you think. 

## create `svy_stat` object

As you discuss in the vignette, the summaries from `srvyr` won't work with `confint` because it doesn't have the `svystat` attributes. I believe
there is a reasonable workaround if we create a `svy_stat` object. For basic summary stats for ungrouped `tbls` I can almost get the meta data working with this code.

```{r eval=FALSE}
survey_stat_ungrouped <- function(.svy, func, x, na.rm, vartype, level) {
  if (class(x) == "factor") {
    stop(paste0("Factor not allowed in survey functions, should ",
                "be used as a grouping variable"))
  }
  if (class(x) == "logical") x <- as.integer(x)
  stat <- func(data.frame(x), .svy, na.rm = na.rm)
  # save survey metadata
  attrs <- attributes(stat)[!grepl("names|class",names(attributes(stat)))]
  vartype <- c("coef", vartype)
  out <- get_var_est(stat, vartype, level = level)
  # append survey metadata
  attributes(out) <- c(attributes(out),attrs)
  out
}
```

Problem is here:

```{r eval=FALSE}
summarise_.tbl_svy <- function(.data, ..., .dots) {
  .dots <- lazyeval::all_dots(.dots, ...)

  survey_funs <- list(
    survey_mean = function(...) survey_mean(.data, ...),
    survey_total = function(...) survey_total(.data, ...),
    survey_ratio = function(...) survey_ratio(.data, ...),
    survey_quantile = function(...) survey_quantile(.data, ...),
    survey_median = function(...) survey_median(.data, ...),
    unweighted = function(...) unweighted(.data, ...)
  )

  out <- lazyeval::lazy_eval(.dots, c(survey_funs, .data$variables))

  # use the argument names to name the output
  out <- lapply(seq_along(out), function(x) {
    setNames(out[[x]], paste0(names(out[x]), names(out[[x]])))
  })
  print(str(out))
  # when I print here I see all the meta data 
  # here is where the meta data is lost
  dplyr::bind_cols(out)
}
```

Because the summarise function can handle multiple summary statistics, there isn't an obvious way to preserve the attributes for each statistic separately. I think the solution is to create a `svy_stat` object that works just like summarise does currently with an additional attribute that is a list of attributes for each statistic. Then we can write `confint.svy_stat` that loops through the individual statistics and call `confint.svystat` from `survey`. 

Here's what I did as a feasibility test, first I appended this to the bottom of summarise so that the `survey` meta data doesn't disappear:

```{r eval=FALSE}
  attr <- lapply(out,attributes)

  out <- dplyr::bind_cols(out)
  attr(out,"Survey Attributes") <- attr
  class(out) <- c("svy_stat",class(out))
  out
```

Then I wrote this:

```{r}
confint.svy_stat<-function(x,parm,level = 0.95) {
  surveyAttributes<-attr(x, "Survey Attributes")
  out<-list()
  for (i in seq_along(surveyAttributes)) {
    # first name is name of estimate
    surveyAttributes[[i]][["names"]]<-surveyAttributes[[i]][["names"]][1]
    # select estimate
    temp <- x[[surveyAttributes[[i]][["names"]]]]
    # add metadata to estimate
    attributes(temp)<-surveyAttributes[[i]]
    # fix quirks in metadata to make it work with confint.svystat
    class(temp)<-c(class(temp)[4])
    attr(temp,"row.names")<-NULL
    # use survey package confint
    out[[surveyAttributes[[i]][["names"]][1]]]<-confint(temp)
  }

    out
}
```

This can probably be done with an apply statement rather than a loop, but this is just a test:

```{r}
suppressPackageStartupMessages(library(srvyr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(survey))
data(api)

srs_design_srvyr <- apisrs %>% as_survey_design(ids = 1, fpc = fpc)

z=srs_design_srvyr %>% summarise(test=survey_mean(api99))

confint(z)
#         2.5 %   97.5 %
# test 606.0647 643.3053
x=srs_design_srvyr %>% summarise(test1=survey_mean(api99),test2=survey_mean(api00))

confint(x)
# $test1
#         2.5 %   97.5 %
# test1 606.0647 643.3053
#
# $test2
#         2.5 %   97.5 %
# test2 638.4559 674.7141

```

Should be able to do the same thing for the other `srvyr` objects and functions. I will continue to work on it.

Kind Regards

**Comment by gergness** [comment]
Hm, interesting. I worry that attributes are fragile, and can hang around even after they've lost meaning. 

Do you think that `srs_design_srvyr %>% summarise(test1 = survey_mean(api99, vartype = c("se", "ci")))` is inadequate? If so, why?

Anyways, here are some edge cases, what do you think we should do in the last 2 cases:
```r
x=srs_design_srvyr %>% summarise(test1=survey_mean(api99),test2=survey_mean(api00))
 
x %>% confint
#> Works

x %>% select(test2, test2_se, test1, test1_se) %>% confint
#> Also works (and gets the answer right)

x %>% rename(test3 = test1, test3_se = test1_se) %>% confint
#>Error in attributes(temp) <- surveyAttributes[[i]] : 
#>  'names' attribute [1] must be the same length as the vector [0]

x %>% select(test1) %>% confint()
#>Error in attributes(temp) <- surveyAttributes[[i]] : 
#>  'names' attribute [1] must be the same length as the vector [0]
```

**Comment by carlganz** [comment]
D'oh, for some reason I didn't fully process the vartype parameter. That's pretty nifty. I guess the only reason to add `confint` functionality is if the user want's to see the actual percentages since `confint` prints 2.5% 97.5% etc. and if you wanted to get several confidence intervals for the same total you'd have to do `srs_design_srvyr %>% summarise(test1 = survey_mean(api99, vartype = c("se", "ci"),level=.95),test2=survey_mean(api99,vartype=c("se","ci"),level=.9))` and then remember that test1_upp refers to .95 confidence and test2_upp refers to .9 confidence.  Alternatively: `x=srs_design_srvyr %>% summarise(test1=survey_mean(api99),test2=survey_mean(api00))
lapply(list(.8,.85,.9,.95),function(z) {confint(x,level=z)})`
would produce CIs that are easily distinguishable. Admittedly, I can now see this isn't super useful. As far as how to deal with the edge cases you presented, we'd have to write a `rename.svy_stat` function that preserves the metadata correctly, which wouldn't be difficult, but I'm sure there are other functions that would present similar problems and dealing with all of them isn't a good investment. Feel free to close this issue if you're not into the idea.

Kind Regards

**Comment by gergness** [comment]
Ha, gotcha. If you've got suggestions for documentation, I'd love to hear them. It's hard to get outside of my own head to make an explanation that other people will understand, though hopefully it has gotten better since you first stated looking at this.

For your use case, I think allowing `level` to take a vector seems best to me.  What do you think?
```
srs_design_srvyr %>% 
  summarise(test1 = survey_mean(api99, vartype = c("se", "ci"), level = c(0.9, 0.65)))
```

If you give it more than one level, then it names the ci variables `test1_low90`, `test1_upp90`, `test1_low65`, `test1_upp65` (I think if there's only one, we can leave off the number, though)

Any interest in tackling this?

**Comment by carlganz** [comment]
That seems like a good idea since it will keep the output tidy. I'll work on it.
