### ISSUE TITLE
Encountering Bugs When Grouped Values in Proportions Are Missing 1 Row

### ISSUE THREAD

**Issue by alexleavitt** [gergness/srvyr#113]
In a situation where I have a dataframe that I want to pivot long in order to ggplot the data easily, with some number of variables all on the same scale (e.g., 7-point Likert), and there are no responses for one of the options (e.g., var5 has value '1' missing, since let's say nobody responded with that), grouping into the survey design throws an error because there aren't balanced values between groups (ie., all other vars have 1-7, but var5 only has 2-7). Is there any way to get around these errors below, or set up a new line in the pipe to avoid this situation?

`df %>% select(group_var, var1, var2, var3, var4, var5, var6) %>%
  pivot_longer(cols = var1:var6, names_to = 'variable', values_to = 'value') %>%
  filter(!is.na(value)) %>%
  filter(!is.na(variable)) %>%
  mutate(value = as.character(value),
         variable = as.character(variable)) %>%
  as_survey_design() %>%
  group_by(group_var, variable, value) %>%
  summarize(proportions = survey_mean(vartype = 'ci', level = c(0.95)),
            total = survey_total()) %>%`

Error examples: "subscript out of bounds" and "Error in cf[parm] + ses %o% fac : non-numeric argument to binary operator"

**Comment by alexleavitt** [comment]
Fast follow-up: it seems that tidyverse group_by() drops 0 rows when using as.character() but not when using as.factor(). Implementing the latter fixed this bug. So maybe the suggestion here is to make the error a bit more verbose and point people to using factors maybe?

**Comment by gergness** [comment]
Sorry I took so long to get to this. That sounds like an error I'd like to fix (even though you have a workaround), but I can't replicate. 

Any chance you can send example data of df that throws this error (ideally using the [reprex package](https://reprex.tidyverse.org))?

Here's my attempt to recreate based on your description, but I don't get the same error.

``` r
library(dplyr)
library(tidyr)
library(srvyr)

df <- tibble(
    group_var = sample(c("a", "b"), 100, TRUE),
    var1 = sample(1:7, 100, TRUE),
    var2 = sample(1:7, 100, TRUE),
    var3 = sample(1:7, 100, TRUE),
    var4 = sample(1:7, 100, TRUE),
    var5 = sample(2:7, 100, TRUE), # var5 has only 2-7
    var6 = sample(1:7, 100, TRUE),
    var7 = sample(1:7, 100, TRUE)
)

df %>% 
    pivot_longer(cols = var1:var6, names_to = 'variable', values_to = 'value') %>% 
    filter(!is.na(value)) %>% 
    filter(!is.na(variable)) %>% 
    mutate(value = as.character(value), variable = as.character(variable)) %>% 
    as_survey_design() %>% 
    group_by(group_var, variable, value) %>% 
    summarize(
        proportions = survey_mean(vartype = 'ci', level = c(0.95)), 
        total = survey_total()
    )
#> # A tibble: 82 x 8
#> # Groups:   group_var, variable [12]
#>    group_var variable value proportions proportions_low proportions_upp total
#>    <chr>     <chr>    <chr>       <dbl>           <dbl>           <dbl> <dbl>
#>  1 a         var1     1          0.176          0.0715            0.281     9
#>  2 a         var1     2          0.157          0.0568            0.257     8
#>  3 a         var1     3          0.118          0.0290            0.206     6
#>  4 a         var1     4          0.0588        -0.00594           0.124     3
#>  5 a         var1     5          0.118          0.0290            0.206     6
#>  6 a         var1     6          0.196          0.0868            0.305    10
#>  7 a         var1     7          0.176          0.0715            0.281     9
#>  8 a         var2     1          0.118          0.0290            0.206     6
#>  9 a         var2     2          0.176          0.0715            0.281     9
#> 10 a         var2     3          0.0784         0.00443           0.152     4
#> # … with 72 more rows, and 1 more variable: total_se <dbl>
```

<sup>Created on 2021-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by gergness** [comment]
Gonna close this because I can't replicate
