### ISSUE TITLE
Feature request: add percent option to survey_mean() for factors

### ISSUE THREAD

**Issue by mlaviolet** [gergness/srvyr#116]
Like `survey::svymean()`, `srvyr::survey_mean()` reports proportions whenever the variable is a factor. In most reports, results are listed as percentages. It would be very convenient to have an argument, say, `percentage = TRUE` to achieve this instead of having to add code to multiply by 100 (default would be `FALSE`, of course). Thanks!

**Comment by gergness** [comment]
Did you know that you can multiply by 100? Feels like this solves the problem well enough to me.

``` r
library(srvyr)
data(api, package = "survey")

dstrata <- apistrat %>%
    as_survey_design(strata = stype, weights = pw)

dstrata %>%
    group_by(awards) %>%
    summarise(pct = survey_mean(vartype = "ci") * 100)
#> # A tibble: 2 x 4
#>   awards   pct pct_low pct_upp
#>   <fct>  <dbl>   <dbl>   <dbl>
#> 1 No      36.1    29.2    43.0
#> 2 Yes     63.9    57.0    70.8
```
