### ISSUE TITLE
Issue with combined_weights specification

### ISSUE THREAD

**Issue by ABSOD** [gergness/srvyr#123]
Hi, srvyr is a great package.  However, It is giving me fits
I have a multi-year file of ACS PUMS data that I want to apply the replicate weights for each year.  
My code:
```
f.ANA_UW <- proc_csv(2010, 2019) # The Unweighted data
f.ANA_UW$YEAR <- as.factor(f.ANA_UW$YEAR)

repwlist <- rep(paste0("PWGTP",1:80))   # The list of replicate weights

# Creating the weighted data 
f.ANA_W <- f.ANA_UW %>% as_survey_rep(
                            variables = c(YEAR), # select grouping variables
                            weights = PWGTP,            # person weight
                            repweights = repwlist,      # list of replicate weights
                            combined_weights = FALSE,    # tells the function that replicate weights are included in the data
                            mse =TRUE,                  # tells the function to calc mse
                            type="other",               # statistical method
                            scale=4/80,                 # scaling set by ACS
                            rscale=rep(1,80))   
```            

This code produces the following error:
```
Error in if (!combined.weights & probably.combined.weights) warning(paste("Data look like combined weights: mean replication weight is",  : 
  missing value where TRUE/FALSE needed
```
Additionally,
I see the following warnings:
```
In mean.default(newX[, i], ...) :
  argument is not numeric or logical: returning NA
```

How do I address this error?  I would appreciate knowing what is going on.
TIA
AB

**Comment by ABSOD** [comment]
I noticed one thing, "combined_weights" in the code above should be set to "TRUE"   My bad.

**Comment by gergness** [comment]
Does the change in `combined_weights` fix your problem?

**Comment by ABSOD** [comment]
Thanks for the reply.
I looked over my data and found the problem.  The weights were character
values.  Once I converted them to numbers (and changed the combined_weights
value), things have been working.
Sorry to take up your time with such an elementary mistake.
AB


On Thu, Jul 15, 2021 at 1:39 PM Greg Freedman Ellis <
***@***.***> wrote:

> Does the change in combined_weights fix your problem?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gergness_srvyr_issues_123-23issuecomment-2D880962309&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=_48y1zlosAiNKKUs9y9scnjxUfv3AM7QUTpY70d48Tw&m=rwPuvh288eqx1ovCluAUg4nFe9Bf171eBrGajuSyB2c&s=ENtoumnzSFxYmmuxkNnCoM91gdMQAcObVRJnsxTTtGQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH2T4FGLALKRYEUSRAMXYDDTX42QHANCNFSM5AOCEAGQ&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=_48y1zlosAiNKKUs9y9scnjxUfv3AM7QUTpY70d48Tw&m=rwPuvh288eqx1ovCluAUg4nFe9Bf171eBrGajuSyB2c&s=Guw5is5Ka1JlqKb2CcmxEfkSativAplwZd1rwcFjtzY&e=>
> .
>


-- 
*Adam Bickford, Ph.D. *
*Data Analyst and Outreach Coordinator*
*Colorado State Demography Office *
*he/him/his*


P 303.864.7753 | 1313 Sherman St., Suite 521, Denver, CO 80203
***@***.*** | https://demography.dola.colorado.gov/
*Please Note:* The staff of the State Demography Office is working
remotely.

*Under the Colorado Open Records Act (CORA), all messages sent by or to me
on this state-owned e-mail account may be subject to public disclosure.*

"For there is always light. If only we’re brave enough to see it." -- Amanda
Gorman
<https://www.rev.com/blog/transcripts/amanda-gorman-inauguration-poem-transcript-the-hill-we-climb>

**Comment by gergness** [comment]
Cool, glad you figured it out, and sorry it was a headache! That's a terrible error message, but I think it comes from the `survey` package itself, so there's nothing can do.

**Comment by gergness** [comment]
For posterity, a more minimal reprex:

``` r
library(survey)
data(scd)
# use BRR replicate weights from Levy and Lemeshow
repweights<-2*cbind(c(1,0,1,0,1,0), c(1,0,0,1,0,1), c(0,1,1,0,0,1),
                    c(0,1,0,1,1,0))

# BUG: User accidentally started with character replicate weights
repweights <- as.character(repweights)

scdrep<-svrepdesign(data=scd, type="BRR", repweights=repweights, combined.weights=FALSE)
#> Warning in grep(repweights, names(data)): argument 'pattern' has length > 1 and
#> only the first element will be used
#> Warning in svrepdesign.default(data = scd, type = "BRR", repweights =
#> repweights, : No sampling weights provided: equal probability assumed
#> Error in if (!combined.weights & probably.combined.weights) warning(paste("Data look like combined weights: mean replication weight is", : missing value where TRUE/FALSE needed
```
