### ISSUE TITLE
svytable/svyciprop and factors

### ISSUE THREAD

**Issue by paulb20** [gergness/srvyr#13]
I'm analysing surveys with mostly categorical data (think American Communities Survey, European Labour Force Surveys). I've been using svytable and svyciprop to get tabulated data out (with svyciprop for conf intervals).

How do I do this with srvyr? Seems to be set up for numeric variables only. Essentially I'd like to pipe on to formattable as well.

**Comment by gergness** [comment]
In general, you'll want to put factor variables as the grouping variables. To get the total or proportion in a particular group, leave x empty for `survey_total()` or `survey_mean()`.

``` r
library(srvyr)
data(api, package = "survey", envir = environment())
dclus1 <- as_survey(apiclus1, id = dnum, weights = pw, fpc = fpc)

# from svytable examples
survey::svytable(~sch.wide+stype, dclus1)
#>         stype
#> sch.wide         E         H         M
#>      No   406.1640  101.5410  270.7760
#>      Yes 4467.8035  372.3170  575.3989

dclus1 %>% 
  group_by(sch.wide, stype) %>%
  summarize(count = survey_total(), 
            pct = survey_mean())
#> Source: local data frame [6 x 6]
#> 
#>   sch.wide  stype     count   count_se       pct     pct_se
#>     (fctr) (fctr)     (dbl)      (dbl)     (dbl)      (dbl)
#> 1       No      E  406.1640  184.84807 0.5217391 0.15023173
#> 2       No      H  101.5410   53.73551 0.1304348 0.06777518
#> 3       No      M  270.7760   96.45819 0.3478261 0.12820856
#> 4      Yes      E 4467.8035 1174.42111 0.8250000 0.04289881
#> 5      Yes      H  372.3170  134.03991 0.0687500 0.02479282
#> 6      Yes      M  575.3989  161.70332 0.1062500 0.02485066
```

Unfortunately, I had a bug, so you couldn't calculate confidence intervals on these until my fixes a few minuts ago. Before the following works, you'll need to install the development version (`devtools::install_github("gergness/srvyr")`)

``` r
dclus1 %>% 
  group_by(sch.wide, stype) %>%
  summarize(count = survey_total(vartype = "ci"), 
            pct = survey_mean(vartype = "ci"))
#> Source: local data frame [6 x 8]
#> 
#>   sch.wide  stype     count   count_low count_upp       pct      pct_low
#>     (fctr) (fctr)     (dbl)       (dbl)     (dbl)     (dbl)        (dbl)
#> 1       No      E  406.1640   43.868389  768.4595 0.5217391  0.227290353
#> 2       No      H  101.5410   -3.778676  206.8607 0.1304348 -0.002402124
#> 3       No      M  270.7760   81.721385  459.8306 0.3478261  0.096541935
#> 4      Yes      E 4467.8035 2165.980443 6769.6266 0.8250000  0.740919871
#> 5      Yes      H  372.3170  109.603557  635.0304 0.0687500  0.020156969
#> 6      Yes      M  575.3989  258.466259  892.3316 0.1062500  0.057543594
#> Variables not shown: pct_upp (dbl)
```

To use the equivalent of `svyciprop()`, you can use `proportion = TRUE` in `survey_mean()`. However, this does not work on factors directly so you'll need to make a logical variable.

```r
dclus1 %>% 
  group_by(sch.wide) %>%
  summarize(pct = survey_mean(stype == "E", proportion = TRUE, vartype = "ci"))
#> Source: local data frame [2 x 4]
#> 
#>   sch.wide       pct   pct_low   pct_upp
#>     (fctr)     (dbl)     (dbl)     (dbl)
#> 1       No 0.5217391 0.2660126 0.7665570
#> 2      Yes 0.8250000 0.7299157 0.8915817
```

If there's something else you think is missing, please try to provide a reproducible example of what you want. You can show how you do it in the survey package if you already have code.

**Comment by seanasdf** [comment]
I have a similar question; I'm analyzing a categorical variable with many levels (the 50 states). If I use the categorical variable as a grouping variable, I can use `survey_mean()` with x empty, and get the proportion of a group represented by each of the categories (to continue the example, the number of individuals from each of the 50 states).  

It would be tedious to create a logical statement for each of the 50 levels of the factor. Is there a way to use the equivalent of `svyciprop` on a factor variable directly? My understanding is that using the `proportion = TRUE` argument makes my confidence intervals more accurate near 0 and 1. Perhaps this is an issue with the underlying survey package that you cannot fix directly in srvyr.

**Comment by gergness** [comment]
Yea, I agree that it's tedious, but it's not supported in the survey package and so I can't really implement it without a lot of extra complexity. I don't know if it is intentional behavior in the survey package, so it may be worth filing a bug over there.

In the meantime, since srvyr always returns data.frames, it plays nicely with `purrr::map_df`:

``` r
library(survey)
library(srvyr)

data(api)

dstrat_srvyr <- as_survey(apistrat, 1, strata = stype, weights = pw, fpc = fpc)

c_levels <- unique(dstrat_srvyr$variables$cname)

purrr::map_df(c_levels, function(cn) {
  dstrat_srvyr %>% 
    summarize(prop = survey_mean(cname == cn, proportion = TRUE, vartype = "ci")) %>%
    mutate(cname = cn)
})
#> # A tibble: 40 x 4
#>          prop    prop_low   prop_upp          cname
#>         <dbl>       <dbl>      <dbl>          <chr>
#>  1 0.22169034 0.164623895 0.29163279    Los Angeles
#>  2 0.05098805 0.025696417 0.09865237        Ventura
#>  3 0.04713755 0.023482746 0.09236664           Kern
#>  4 0.04986116 0.026413753 0.09215262      San Diego
#>  5 0.04657410 0.023875666 0.08888677 San Bernardino
#>  6 0.03858734 0.018856645 0.07733600      Riverside
#>  7 0.06282531 0.033550909 0.11461351         Fresno
#>  8 0.03512431 0.015324223 0.07846893        Alameda
#>  9 0.07427510 0.042795624 0.12586538         Orange
#> 10 0.01671295 0.004970443 0.05467247           Inyo
#> # ... with 30 more rows
```

**Comment by seanasdf** [comment]
Using Purr seems like a good solution! Thank you!
