### ISSUE TITLE
missing value rows

### ISSUE THREAD

**Issue by Argyris36** [gergness/srvyr#146]
Hi there, 

Great package, well done. 

When I run the survey_mean command, it estimates percentages of system missing variables as well: I get rows with NAs that mess up the total, see screenshot below.

Any advice gratefully received. 

a
![Screenshot 2022-09-17 at 10 16 27 (2)](https://user-images.githubusercontent.com/61797488/190849712-f0a25b28-47a1-4bba-bb15-b91719b13853.jpg)

**Comment by bschneidr** [comment]
Hi @Argyris36 ,

In this case, you can use `filter()` prior to calling `summarize()`: 

```r
my_survey %>% 
   filter(!is.na(Gender)) %>%
   summarize(prop = survey_mean())
```

**Comment by gergness** [comment]
Documentation improved and now has a warning
