### ISSUE TITLE
Support for R 3

### ISSUE THREAD

**Issue by Jollywatt** [gergness/srvyr#170]
Does this package support R version 3?
According to https://cran.r-project.org/package=srvyr it depends onR (≥ 3.1.2), but installing it on R 3.6.0 fails because of this line which contains the modern pipe:

https://github.com/gergness/srvyr/blob/1917f75487fa40f2ea6fd4e33323cd9278afb356/R/survey_statistics.r#L870

**Comment by gergness** [comment]
I'll replace it with a `magrittr` pipe, but I don't really have the resources to ensure backwards compatibility. I will also remove the misleading line from the DESCRIPTION
