### ISSUE TITLE
survey assumes default order from SQL query results (I think), is this okay?

### ISSUE THREAD

**Issue by gergness** [gergness/srvyr#21]
Working through the database code from survey, I am pretty sure that it depends on SQL queries always returning results in the same order, because it stores the survey variables (such as weights, strata, etc.) in memory and pairs them together with results from a SQL query. Google searches seem to confirm my suspicion that this isn't a good idea (for example [stackoverlow](http://stackoverflow.com/questions/1793147/sql-best-practice-to-deal-with-default-sort-order)).

I'm not sure which of the following are true:

1) survey does in fact request the data to be ordered somewhere I haven't seen. srvyr will need to as well.

2) The DB software that survey advertises as working does in fact have a default order and so its okay. If so, srvyr should probably provide a check for this. [PostgresSQL](https://www.postgresql.org/docs/9.1/static/queries-order.html) in particular says that you shouldn't depend on order. Sqlite doesn't even implement windowing functions which seems to also imply that order isn't guaranteed (but SQLite is what survey is tested on).

3) Because the survey package's queries are so simple, it's okay to assume that the order is always the same (no join_bys or other complicated stuff). This would be a little harder to guarantee in srvyr's current implementation because there is a possibility that someone has already passed in a complicated query (though maybe that's rare enough that we'll be okay?)

4) None of the above are true and srvyr should do something to ensure that the results are ordered in the way it expects.

Any ideas @ajdamico ? I see that you're on the author list of MonetDB.R in addition to having written all of those asdfree examples.

**Comment by ajdamico** [comment]
hi, 1) and 2) are both not true..  the survey package exclusively uses `SELECT colname FROM tablename` which should be safe even if not guaranteed.  but i am not sure about 3) and i think you're right to worry that `tablename` might get sorted differently somewhere during a dplyr call.  safest strategy is probably just a bunch of testthats that trigger the subsets and updates inside the survey package's `dbiupdate.R`?  your easiest second testthat option to get running in travis-ci would probably be `library(MonetDBLite)` which should require minimal code changes from what you already have with `library(RSQLite)` but the actual database follows the sql standard more strictly.

https://github.com/hannesmuehleisen/MonetDBLite/blob/master/tests/testthat/test_03_dplyr.R

**Comment by gergness** [comment]
Gotcha, thanks. My current strategy has been to have a `dplyr::tbl_lazy` serve as the survey object's `$variables` slot, which routed around all of survey's database code. I'd prefer to have a system that works regardless of what db you're using, or at the very least fail if you're using an incompatible type.

**Comment by gergness** [comment]
Ha, in some sort of sick joke my solution relied on "ORDER BY", which makes my MonetDB support not automatic.

 @ajdamico do you know of a way to determine which database systems have this behavior?

For my future reference -  MonetDB discussion on ordering and dplyr from newsgroup: https://www.monetdb.org/pipermail/users-list/2013-October/006887.html
(TL;DR - can't use order by on subqueries, but can on results, so we'd need to request the ID column in final results and remove after it has been pulled into R)

**Comment by ajdamico** [comment]
hi, yep, subquery ORDER BY is not part of the sql standard.  just test if a database throws an error?

	library(DBI)

	mdb <- dbConnect( MonetDBLite::MonetDBLite() )
	ldb <- dbConnect( RSQLite::SQLite() )

	dbGetQuery( ldb , "SELECT * FROM ( SELECT ( 1 ) AS a ORDER BY a DESC )" )
	dbGetQuery( mdb , "SELECT * FROM ( SELECT ( 1 ) AS a ORDER BY a DESC )" )
	
	
i would wager that >90% of database-backed survey design users are using sqlite or monetdb. if you want to be scientific about it, you could look at cranlogs to see which database r packages have been downloaded during the same session as `survey` package downloads.
