### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by wangyuchen** [gergness/srvyr#26]
Hi, 

I noticed that most of the `srvyr` statistics functions renamed the output (e.g. added `_se`), except for a few cases, like `survey_mean` and `survey_total`. I ran into a small problem because of that. 

```
library(survey)
library(srvyr)
data(api)

dstrata <- apistrat %>%
    as_survey_design(strata = stype, weights = pw)

dstrata %>%
    group_by(stype) %>%
    summarise(api99 = survey_mean(api99),
              api00 = survey_mean(api00),
              api_diff = survey_mean(api00 - api99))
```

The output will have names `api99`, `api99_se`, `api00`, `api00_se` and so on. These are all valid names, it's just when I try to use `tidyr` to re-organize the table, they don't fit into the `tidyr` routines that well. 

For example, normally I would do: `tidyr::gather`, `tidyr::extract` and `tidyr::spread` to get a variable by statistics table (and also by group), but in this case it won't work because the mean or total statistics don't end with "_mean" or "_total". 

Since each survey statistics comes with a standard error, that is, in some sense, making all the `summarise` call a `summarise_at` call with a function list. 

```
dplyr::summarise_at(iris, .cols = vars(starts_with("Sepal")), .funs = funs(mean, sd))
```

Consider the output of this call, even when it's unnamed, the output columns will have `_mean` and `_sd` in their names, so that it will be easier to work with the names later. 

Is it possible that `srvyr` go with this approach as well?

**Comment by gergness** [comment]
Yea, I agree that the current behavior isn't right. I'm hoping to work on srvyr a bit in the next few weeks and will take a look then.

**Comment by wangyuchen** [comment]
I have to use `survey` all the time for survey data analysis. A lot of data manipulation needed `dplyr`, but it's really hard to make `dplyr` work with `survey` because of the legacy style API design. However powerful the `survey` package is, it's a pain to use and incorporate into other systems.

`srvyr` is a brilliant idea, I tried a few other things to make `dplyr` work with `survey` but they all didn't work out. For this issue, one thing I think may worth trying: in `srvyr`, every summarize is actually a summarize_at, in that it provides both point estimate and standard error at the same time. So, can summarize be implemented that way? Would love to hear your comments. Will you be willing to accept pull requests if I were to make that change? Thanks.

**Comment by gergness** [comment]
Hm, I'm just realizing that I never submitted to CRAN after I added summarize_at. Have you installed the github version?

I think a problem is that srvyr is breaking convention by allowing a single function to return multiple columns, so it doesn't totally fit into the `mutate_at()` framework either. I don't think it'd be worth all of the extra typing and computation of having separate functions for mean, se, and CIs. Therefore, I think that it makes sense to have srvyr support `summarize()` (in addition to `summarize_at()`

**Comment by wangyuchen** [comment]
Thanks for your reply. I just checked out the GitHub version and it does have all the `_at`, `_if` and `_all` functions. 

I didn't understand why you said:

> I don't think it'd be worth all of the extra typing and computation of having separate functions for mean, se, and CIs.

I thought all the `survey_funs` functions are to be used for that purpose? I don't mean to create separate summary statistics functions either. Perhaps I'm missing the whole picture here, but what I'm suggesting is to base the summarize on the `summarize_at` methods.

Currently `dplyr` implements all of those `_at`, `_if` and `_all` functions on top of the `summarize_` generic. As you said, `dplyr`'s convention only allow each `summarize` function to return a single column, so it's nature to build `summarize` first, and all other extensions on top of that. However, in the `tbl_svy` case, one more restriction is that usually at least two columns will be returned in every summarize. If `dplyr`'s behavior is to be imitated, then `summarize_at` with `funs` being a list of at least two functions should be the most frequently used verb, and summarize should be reserved for when a single mean or se is needed. 

IMO, the advantages of doing that are:
1. The exact same behavior as `dplyr` verbs, so `dplyr` users know what to expect.
2. Automatic naming scheme implemented by `dplyr`. When funs is a list of functions, `dplyr` takes care of the naming issue. 

Also, because of the restrictions "srvyr" has, another escape hatch can be provided. For example:

```
summarize2 <- function(data, ...) {
  # extract dots like foo(bar) to fun = foo and var = bar
  # foo could be redirected to a list of mean and se
  summarize_at(data, .vars = var, .funs = funs(fun))
}
summarize2(x_new = survey_mean(x))  # will return x_new_mean and x_new_se columns
```

This is a function uses `dplyr::summarize`'s grammar but with different behavior from it. Currently this is somehow like `srvyr::summarize`. By requiring users to type a different name maybe it's easier they don't get confused easily. 

This is only my personal opinion from using this package for a few days. I know there must be other practical concerns. Would love to hear your comments. Thanks.

**Comment by gergness** [comment]
Yea, thanks for you input. The "tidyverse" has developed a lot since I first started it, and so I agree that it feels a little crusty.

I'm not sure I totally follow your suggestion, though. I think you are saying that your proposed API look looks like this:
```
svy %>% 
  summarize_at("api99", funs(survey_mean, survey_mean_se))
```

If so, I don't love it for a couple of reasons:
1) I can't think of a way to do this without repeating all of the calculations for the "survey_mean" and "survey_mean_se" separately which could make it really slow.
2) The naming scheme is still pretty bad. I think that the name of the function has to be "survey_mean" to differentiate it from normal means, but this means that the variable name (with multiple variales summarized) would default to `api99_survey_mean` and `api99_survey_mean_se` which would still be annoying for tidyr.
3) I agree that technically the only dplyr function that outputs more than 1 column is `summarize_at()`, but I feel that people's understanding of the `summarize()` function is much higher than the `summarize_at()` functions. In most cases, if you just want the mean, you could use a regular `tbl` and `weighted.mean()` to calculate the weighted mean. So `srvyr`'s main goal is to give the other statistics in an easy format.
4) You can't calculate the mean on one variable and the median of another, all variables will get all statistics.

**Comment by gergness** [comment]
I think list columns may be the answer, but I'd want to make it really easy to do common operations because list columns can also be difficult to deal with.

**Comment by wangyuchen** [comment]
Thanks for the reply. My use case is that I need to run the same summary statistics to a lot of variables. Normally I would use `tidyr::gather` and `group_by`, but in the survey data case I can't do that. So it brought me back to the for-loop or lapply days and it's a huge pain. I tried to use `srvyr`, and it brought me back to the original issue -- I can't manipulate the generated data frame because of the names. I guess this is the main point of this issue: `srvyr` is implemented to use `dplyr` syntax to do common operations, but I was trying to scale it up and use it with other tools like I would with `dplyr`. 


I'm still thinking about your first point, and I agree with 3 and 4. 


For point 2, I think something like this will do:
```
library(dplyr)
summarise_at(iris, .cols = vars(starts_with("Sepal")), 
                   .funs = funs(m = mean, m_se = sd(.) / sqrt(n())))

#   Sepal.Length_m Sepal.Width_m Sepal.Length_m_se Sepal.Width_m_se
# 1       5.843333      3.057333        0.06761132       0.03558833
```

And even it's all ending with "survey_mean" and "survey_mean_se", it's too long but it's still easier to work with using a simple regular expression.


For point 3, I guess what I'm trying to say is preserving `summarize` and `summarize_at`'s behavior in `dplyr`, but providing **another function** that generates two columns with one call (current `srvyr` behavior). But this is just a personal opinion, I can see that re-implement "summarize" with a slightly different behavior is reasonable too. What I had in mind is:

1. `summarize` just call `dplyr::summarize`, any function, on any variables.
2. `summarize_at` always returns at least two cols when it's called, applied to the same variable. 
3. `summarize2` (or some other name) use `summarize` syntax, but returns at least two columns for each call, on any variables. This is the current `srvyr::summarize`. 

Or even add in an option like `summarize(data, ..., return_se = FALSE)`, so that 3 and 1 can be combined? This is getting complicated.. Excuse me for just throwing it out here. I'll think about it more tomorrow. Thanks for the discussion!

**Comment by wangyuchen** [comment]
```
library(survey)
library(srvyr)
data(api)

dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw) %>%
  group_by(stype)

dstrata_grp %>%
    summarise_at(.cols = c("api99", "api00"), .funs = funs(mean = survey_mean))

```

Just realized that this works. Check the name it outputs! This solved my problem for now. `dplyr` is a miracle.

**Comment by gergness** [comment]
Cool, glad that works for you. (That's why I asked if you had the github version, I haven't pushed those changes to CRAN yet).

I still think there is room for improvement, so thanks for putting in your 2 cents.

**Comment by gergness** [comment]
After thinking about this some more, I decided it's not worth it to break existing code by changing column name defaults.
