### ISSUE TITLE
failing test for grouped proportions

### ISSUE THREAD

**Issue by tslumley** [gergness/srvyr#37]
The test for grouped proportions in `test_survey_proportion.R` is failing because of a difference in row names between srvyr and survey output. You probably know this, but I have to be able to tell CRAN I've told you because it looks like a broken reverse dependency for survey.

```
> test_that("grouped proportion works correctly",
+           expect_equal(out_srvyr, out_survey))
Error: Test failed: 'grouped proportion works correctly'
* `out_srvyr` not equal to `out_survey`.
Rows in x but not y: 3. Rows in y but not x: 3. 
> out_srvyr
# A tibble: 3 x 4
   stype     x     x_low     x_upp
  <fctr> <dbl>     <dbl>     <dbl>
1      E  0.73 0.6357170 0.8121219
2      H  0.32 0.1971594 0.4625013
3      M  0.48 0.3391986 0.6229864
> out_survey
# A tibble: 3 x 4
   stype     x     x_low     x_upp
* <fctr> <dbl>     <dbl>     <dbl>
1      E  0.73 0.6357170 0.8121219
2      H  0.32 0.1971594 0.4625013
3      M  0.48 0.3391986 0.6229864
```

**Comment by gergness** [comment]
Thanks! And sorry for any inconvenience - I've got an update coming to srvyr soon.

**Comment by gergness** [comment]
I can't actually replicate this, but seems likely that this has to do with the changes going on in tibble lately. 

I've updated the tests to ignore the row.names attribute when comparing data.frames.
