### ISSUE TITLE
Error with multiple quantiles on grouped data

### ISSUE THREAD

**Issue by iantperry** [gergness/srvyr#38]
I get an error when trying to calculate multiple quantiles on grouped data.

To reproduce:
```R
library(survey)
data(api)

dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw)

dstrata %>%
  group_by(awards) %>%
  summarise(api99 = survey_quantile(api99, c(0.25, 0.5, 0.75)))
```
The error is:
```Error in `[.data.frame`(stat, c("ci_l", "ci_u")) : undefined columns selected```

It can calculate multiple quantiles without grouping, or a single quantile with grouping, just not multiple quantiles with grouping.

**Comment by gergness** [comment]
Bummer, sorry about that, but thanks for the clear bug report! I am able to reproduce over here and I'll try to take a look soon.

**Comment by gergness** [comment]
Thanks!
