### ISSUE TITLE
Obtaining design effect from survey_mean

### ISSUE THREAD

**Issue by mlaviolet** [gergness/srvyr#39]
NCHS has published [standards](https://www.cdc.gov/nchs/data/series/sr_02/sr02_175.pdf) for presentation of proportions. For complex surveys the standards are based on effective sample size and confidence interval width. The recommended method for confidence intervals is the Korn-Graubard method, implemented in `survey` by the `"beta"` argument to `svyciprop`. For programming the standards, it would be very useful to get the design effect (for effective sample size) and confidence interval with a single call to `survey_mean`. When I try this without a grouping variable, the design effect does not appear; with a grouping variable an error is thrown. Here's what I've tried. Please advise. Thanks!

```
library(srvyr)
data(api, package = "survey")
dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw)

dstrata %>%
summarise(high_api = survey_mean(api00 > 875, deff = TRUE, proportion = TRUE, 
                        vartype = "ci", prop_method = "beta"))
# # A tibble: 1 x 3
# high_api high_api_low high_api_upp
#        <dbl>        <dbl>        <dbl>
#   1   0.0318      0.00997       0.0744

dstrata %>% 
  group_by(stype) %>%
  summarise(high_api = survey_mean(api00 > 875, deff = TRUE, proportion = TRUE, 
                          vartype = "ci", prop_method = "beta"))`
# Error in deff.svyby(stat) : 
#   object does not have design effect information
```

**Comment by gergness** [comment]
Sorry about that, I can replicate over here; thanks for the easily reproducible example. 

I'll try to take a closer look soon, but I might not be able to fix this in srvyr. The survey package itself has trouble with this combination of settings (design effect + svyciprop):

``` r
suppressPackageStartupMessages(library(survey))
data(api)

dstrata <- svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat)

# No design effects
svyciprop(~api00 > 875, dstrata, method = "beta", deff = TRUE)
#>                        2.5% 97.5%
#> api00 > 875 0.03184 0.00997  0.07

# Get NULL back
deff(svyciprop(~api00 > 875, dstrata, method = "beta", deff = TRUE))
#> Warning in deff.default(svyciprop(~api00 > 875, dstrata, method = "beta", :
#> object has no design effect information
#> NULL
```

**Comment by gergness** [comment]
From an email exchange with Professor Lumley:
> The point of svyciprop is that the variance of the proportion isn't a good error summary, so I don't really think it's useful.  The design effect from svymean would be the one if someone wanted one.

As a workaround, if you really need to use proportion with the beta method and a design effect you could have 2 calls to `survey_mean()`.
``` r
library(srvyr)
data(api, package = "survey")
dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw)

dstrata %>%
  summarise(
    high_api = survey_mean(
      api00 > 875, deff = TRUE, proportion = TRUE,  vartype = "ci", prop_method = "beta"
    ),
    high_api_deff = survey_mean(api00 > 875, deff = TRUE)
  ) %>%
  select(-high_api_deff, -high_api_deff_se, high_api_deff = high_api_deff_deff)
#> # A tibble: 1 x 4
#>   high_api high_api_low high_api_upp high_api_deff
#>      <dbl>        <dbl>        <dbl>         <dbl>
#> 1   0.0318      0.00997       0.0744          1.39
```

I admit this isn't the greatest solution, but it matches the behavior of the survey package and I like to rely on Professor Lumley's expertise on these kinds of matters.

I do think that I should update srvyr's behavior here though, there should be a clear error for both the grouped and ungrouped case when combining prop and deff options. Part of the confusion comes from the way that srvyr combines the survey package's `svymean` and `svyciprop` functions into a single function, which I thought was a good idea at the time, but am not so sure anymore. Too late to change, but I do want to reduce confusion.

**Comment by mlaviolet** [comment]
According to the NCHS standards the first step is to look at the effective sample size, which is where the design effect comes in.  If the effective sample size is inadequate, then the estimate is suppressed and there's no need to call `svyciprop`. Otherwise the estimate is computed and evaluated for whether it's sufficiently precise. So it turns out you don't want both at the same time anyway and there's no need to modify the `srvyr` behavior. Thanks for looking into this and for supporting this very useful package.
