### ISSUE TITLE
Calculate Deff using "replace"

### ISSUE THREAD

**Issue by mandes95** [gergness/srvyr#46]
Dear Gergness,
How if I want to calculate the deff value using "replace" (not logical value) like what can I do by using survey package? I can't found any documentation for this.

thanks for your help, this package is really great.

**Comment by gergness** [comment]
Thanks! I hadn't seen that "replace" was an acceptable input to the deff argument, I'll need to make some changes.

reprex:
``` r
library(survey)
library(srvyr)

data(api)

dstrat<-svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)

svymean(~api99, dstrat, deff = "replace")
#>           mean       SE   DEff
#> api99 629.3948   9.9639 1.2021

dstrat %>% 
  as_survey() %>% 
  summarize(api99 = survey_mean(api99, deff = "replace"))
#> Error in if (deff) {: argument is not interpretable as logical
```

<sup>Created on 2018-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by gergness** [comment]
Thanks!
