### ISSUE TITLE
postStratify in srvyr?

### ISSUE THREAD

**Issue by tscarelli** [gergness/srvyr#50]
Hello! 

Is it possible to use `srvyr` to generate a survey design object similar to what `survey::postStratify` would create?

**Comment by gergness** [comment]
Currently the best route is to use `srvyr::as_survey` after calling `survey::postStratify`.

Adapting the survey package documentation:
``` r
library(survey)
library(srvyr)

data(api)
dclus1 <- svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
rclus1 <- as.svrepdesign(dclus1)

# post-stratify on school type
pop.types <- data.frame(stype=c("E","H","M"), Freq=c(4421,755,1018))

rclus1p<-postStratify(rclus1, ~stype, pop.types)
svymean(~api00, rclus1p)
#>         mean     SE
#> api00 642.31 26.934

# srvyr equivalent
rclus1p_srvyr <- rclus1 %>% 
  postStratify(~stype, pop.types) %>% 
  as_survey()
  
rclus1p_srvyr %>% 
  summarize(api00 = survey_mean(api00))
#> # A tibble: 1 x 2
#>   api00 api00_se
#>   <dbl>    <dbl>
#> 1  642.     26.9
```

<sup>Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I can see why you'd want a `srvyr::postStratify` to do this more directly, but I think it's outside the scope of srvyr. There are a lot of functions in the survey package, and I can't support wrapping all of them, so I have to draw a line somewhere (even if it's arbitrary, and in this particular case doesn't require much work).
