### ISSUE TITLE
[Bug?] Raked design gives different result from filtering

### ISSUE THREAD

**Issue by bschneidr** [gergness/srvyr#51]
When I use `filter()`, the result unexpectedly differs depending on whether the survey design includes raked weights or just strata-based weights.

In the example below from the API schools data, I filter the data to exclude results from Alameda county. When I filter the `survey_design` object that includes raked weights, the result from calling `filter()` surprisingly still includes a row for Alameda county. In contrast, the result from using `filter()` on the `survey_design` object with just cluster-based weights does not include a row from Alameda county.

``` r
library(survey)
library(srvyr)
#> 
#> Attaching package: 'srvyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter


data(api)


# Declare basic clustered design ----
  cluster_design <- as_survey_design(.data = apiclus1,
                                     id = dnum,
                                     weights = pw,
                                     fpc = fpc)

# Add raking weights for school type ----
  pop.types <- data.frame(stype=c("E","H","M"), Freq=c(4421,755,1018))
  pop.schwide <- data.frame(sch.wide=c("No","Yes"), Freq=c(1072,5122))

  raked_design <- rake(cluster_design,
                       sample.margins = list(~stype,~sch.wide),
                       population.margins = list(pop.types, pop.schwide))
  
# Compare result of filtering ----
  # Note that the first row is 'Alameda'
  raked_design %>% 
    filter(cname != "Alameda") %>% 
    group_by(cname) %>% 
    summarize(proportion = survey_mean())
#> # A tibble: 11 x 3
#>    cname       proportion proportion_se
#>    <chr>            <dbl>         <dbl>
#>  1 Alameda         0             0     
#>  2 Fresno          0.0252        0.0260
#>  3 Kern            0.0135        0.0141
#>  4 Los Angeles     0.0863        0.0765
#>  5 Mendocino       0.0302        0.0303
#>  6 Merced          0.0273        0.0283
#>  7 Orange          0.0872        0.0856
#>  8 Plumas          0.0659        0.0590
#>  9 San Diego       0.304         0.171 
#> 10 San Joaquin     0.213         0.182 
#> 11 Santa Clara     0.147         0.0996
  
  # Note that the name 'Alameda' is nowhere to be found
  cluster_design %>% 
    filter(cname != "Alameda") %>% 
    group_by(cname) %>% 
    summarize(proportion = survey_mean())
#> # A tibble: 10 x 3
#>    cname       proportion proportion_se
#>    <chr>            <dbl>         <dbl>
#>  1 Fresno          0.0233        0.0248
#>  2 Kern            0.0116        0.0125
#>  3 Los Angeles     0.0872        0.0782
#>  4 Mendocino       0.0233        0.0248
#>  5 Merced          0.0233        0.0248
#>  6 Orange          0.0930        0.0926
#>  7 Plumas          0.0523        0.0543
#>  8 San Diego       0.320         0.185 
#>  9 San Joaquin     0.215         0.184 
#> 10 Santa Clara     0.151         0.104
```

At a certain level, this doesn't seem to affect the accuracy of the statistics (in both cases, the count for Alameda is effectively zero, either implicitly or explicitly). However, the display of an explicit zero for 'Alameda' in the result from `filter(raked_design, cname != "Alameda")` could end up being mistaken as an actual estimate rather than as an indication that an estimate was intentionally not produced.

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2019-03-27                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.1)
#>  callr         3.2.0   2019-03-15 [1] CRAN (R 3.5.3)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
#>  devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.1)
#>  dplyr         0.8.0.1 2019-02-15 [1] CRAN (R 3.5.2)
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.5.2)
#>  fansi         0.4.0   2018-10-05 [1] CRAN (R 3.5.1)
#>  fs            1.2.7   2019-03-19 [1] CRAN (R 3.5.3)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.5.3)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
#>  knitr         1.22    2019-03-08 [1] CRAN (R 3.5.3)
#>  lattice       0.20-38 2018-11-04 [2] CRAN (R 3.5.3)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
#>  Matrix      * 1.2-15  2018-11-01 [2] CRAN (R 3.5.3)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
#>  pillar        1.3.1   2018-12-15 [1] CRAN (R 3.5.1)
#>  pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.5.3)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.1)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
#>  processx      3.3.0   2019-03-10 [1] CRAN (R 3.5.3)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.1)
#>  purrr         0.3.2   2019-03-15 [1] CRAN (R 3.5.3)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.5.3)
#>  remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.1)
#>  rlang         0.3.2   2019-03-21 [1] CRAN (R 3.5.3)
#>  rmarkdown     1.12    2019-03-14 [1] CRAN (R 3.5.3)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)
#>  srvyr       * 0.3.4   2019-01-20 [1] CRAN (R 3.5.2)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  survey      * 3.35-1  2019-01-29 [1] CRAN (R 3.5.2)
#>  survival    * 2.43-3  2018-11-26 [2] CRAN (R 3.5.3)
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.1)
#>  tibble        2.1.1   2019-03-16 [1] CRAN (R 3.5.3)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.1)
#>  usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.1)
#>  utf8          1.1.4   2018-05-24 [1] CRAN (R 3.5.1)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
#>  xfun          0.5     2019-02-20 [1] CRAN (R 3.5.2)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
#> 
#> [1] C:/Users/Ben Schneider/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.3/library
```

</details>

**Comment by gergness** [comment]
Hm, I'll take a closer look soon, but I suspect there's not much I can do because this behavior matches what is in the survey package.

(Many thanks for making such a great reprex!)
``` r
library(survey)

data(api)


# Declare basic clustered design ----
cluster_design <- svydesign(data = apiclus1,
                                   id = ~dnum,
                                   weights = ~pw,
                                   fpc = ~fpc)

# Add raking weights for school type ----
pop.types <- data.frame(stype=c("E","H","M"), Freq=c(4421,755,1018))
pop.schwide <- data.frame(sch.wide=c("No","Yes"), Freq=c(1072,5122))

raked_design <- rake(cluster_design,
                     sample.margins = list(~stype,~sch.wide),
                     population.margins = list(pop.types, pop.schwide))

# also introduces the Alameda row...
svymean(~cname, subset(raked_design, cname != "Alameda"))
#>                      mean     SE
#> cnameAlameda     0.000000 0.0000
#> cnameFresno      0.025186 0.0260
#> cnameKern        0.013538 0.0141
#> cnameLos Angeles 0.086321 0.0765
#> cnameMendocino   0.030172 0.0303
#> cnameMerced      0.027292 0.0283
#> cnameOrange      0.087232 0.0856
#> cnamePlumas      0.065915 0.0590
#> cnameSan Diego   0.304145 0.1708
#> cnameSan Joaquin 0.213357 0.1821
#> cnameSanta Clara 0.146842 0.0996

svymean(~cname, subset(cluster_design, cname != "Alameda"))
#>                      mean     SE
#> cnameFresno      0.023256 0.0248
#> cnameKern        0.011628 0.0125
#> cnameLos Angeles 0.087209 0.0782
#> cnameMendocino   0.023256 0.0248
#> cnameMerced      0.023256 0.0248
#> cnameOrange      0.093023 0.0926
#> cnamePlumas      0.052326 0.0543
#> cnameSan Diego   0.319767 0.1854
#> cnameSan Joaquin 0.215116 0.1844
#> cnameSanta Clara 0.151163 0.1044
```

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bschneidr** [comment]
Ahh, ok. Thanks for pointing that out!
I'll try to figure out if this is considered a bug from the standpoint of the `survey` package, or if there's some motivation I'm missing behind this behavior.

One of the rarely-mentioned benefits of using the fantastic `srvyr` package is that it's so much easier to read through the code and work through Github issues and conversations, compared to trying to read through the `survey` package's news files and diffs on the Github CRAN mirror. Thanks for all the work you've put into making `srvyr` and `survey` much more accessible.

**Comment by gergness** [comment]
Ha, thanks for the kind words! I think some of it is just a difference of preferences from the old guard - Professor Lumley is pretty good about email. Let me know if you hear back.

**Comment by bschneidr** [comment]
I did some more digging and it seems the issue is related to unique behavior that appears when you try to select rows using indices.

    nrow(cluster_design[1:10,])
    #> 10
    nrow(raked_design[1:10,])
    #> 183

I'm still trying to figure out whether this is a bug or intended behavior that could maybe be better-document.
[Why do attempts to filter a raked survey design object fail?](https://stackoverflow.com/questions/55384157/why-do-attempts-to-filter-a-raked-survey-design-object-fail)

**Comment by bschneidr** [comment]
Sorry for accidentally closing the issue.

I've done some more research and found that subsetting a raked design object is implemented in the `survey` package in kind of a strange way.

When you subset a normal design object (i.e. an object without raking or poststratification), essentially every part of the object is subsetted (`my_survey_design$variables`, `my_survey_design$prob`, etc.). In contrast, when you subset a raked/calibrated object, none of the rows or elements in the various components are dropped. Rather, the probabilities in the `prob` part of the object (i.e. my_survey_design$prob) are updated, so that the entries corresponding to the removed rows are changed to `Inf`.

### Comparison of subsetting raked vs. clustered designs


    # Filter the two different design objects ----
    subset_from_raked_design <- subset(raked_design, cname != "Alameda")

    subset_from_cluster_design <- subset(cluster_design, cname != "Alameda")

    # Count number of rows in the subsets
      nrow(subset_from_raked_design)
    #> [1] 183
      nrow(subset_from_cluster_design)
    #> [1] 172
      
    # Compare the prob component
      filtered_cluster_probs <- subset_from_cluster_design$prob
      length(filtered_cluster_probs)
    #> [1] 172
      
      filtered_raked_probs <- subset_from_raked_design$prob
      length(filtered_raked_probs)
    #> [1] 183
      
      unfiltered_raked_probs <- raked_design$prob
      length(unfiltered_raked_probs)
    #> [1] 183
      
      table(filtered_raked_probs == unfiltered_raked_probs)
    #> 
    #> FALSE  TRUE 
    #>    11   172

     filtered_raked_probs[1:5]
    #> Inf Inf Inf Inf Inf

**Comment by gergness** [comment]
Ah, I knew this sounded familiar:

https://github.com/gergness/srvyr/issues/33#issuecomment-357539372

I'm not sure it's exactly a desired attribute of the survey package, but it might not be fixable.

**Comment by bschneidr** [comment]
There we go, that settles it. So this is 100% a result of some quirks of the `survey` package, maybe something that should be changed or just better documented. I'll give this some thought and maybe send Professor Lumley an e-mail offering some documentation or a code update. I'll post back here with any updates.

Thanks for all your help! Your work on this package and the underlying `survey` package is making it so much easier for folks to do high-quality survey analysis.
