### ISSUE TITLE
filter_at syntax inconsistency between dplyr and srvyr

### ISSUE THREAD

**Issue by dcaseykc** [gergness/srvyr#57]
Hi Greg (and Ben?),

I'm having some difficulty using the `filter_at` command family. For example:

```
library(srvyr, warn.conflicts = FALSE)
data(api, package = "survey")

#set some data as NA
apistrat$sch.wide[1] = NA
apistrat$cnum[2] = NA

filter_vars = c('sch.wide', 'cnum')

dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw)

#Attempt 1
dstrata %>% filter_at(filter_vars, ~!is.na(.)) %>% summarize(a = unweighted(n()))

#Attempt 2
dstrata %>% filter_at(filter_vars, all_vars(!is.na(.))) %>% summarize(a = unweighted(n()))

#Attempt 3, not survey
apistrat %>% filter_at(filter_vars, all_vars(!is.na(.))) %>% summarize(a = n())

#Attempt 4, not survey
apistrat %>% filter_at(filter_vars, ~!is.na(.)) %>% summarize(a = n())
```

Attempts 1 and 2 return the following error, whereas the native dplyr equivalents seem to behave:
```
Error: `.preserve` (`.preserve = .preserve`) must not be named, do you need `==`?`
```

I'm not the most familiar with the dplyr interface, so apologies if I'm confusing the underlying issue.

**Comment by gergness** [comment]
I'm able to replicate, and know the source of the problem, just need to work out what dplyr's `.preserve` is supposed to do.

**Comment by gergness** [comment]
I think I've got something that fixes this, but need to take some more time to test that this doesn't break something else. You can install it by running command `devtools::install_github("gergness/srvyr", ref = "fix57")`

Thanks!

**Comment by bschneidr** [comment]
I think the edits you made fixed the problems with `filter_at()`. In the test file of pull request #60 , all of the tests for `filter_at()` pass.

**Comment by gergness** [comment]
fix now in master, sorry lost track of this
