### ISSUE TITLE
problem with deff in survey_ratio with as_survey_rep

### ISSUE THREAD

**Issue by jpferreira33** [gergness/srvyr#81]

**Comment by jpferreira33** [comment]
Hi!
The function survey_ratio doesn't compute de deff when the design is defined with replicates (e.g. bootstrap)

# define el diseño por ultimo conglomerado
design = df %>% as_survey_design(ids=upm, strata=strata, weights=w) 
design_boot =  design %>% as_survey_rep(type="subbootstrap",replicates=100)
design_boot %>% summarise(survey_ratio(x, y,deff=TRUE))
Error in rval[i, j] : incorrect number of dimensions

**Comment by bschneidr** [comment]
This is actually an issue with the underlying `survey` package. Here's a reproducible example:

``` r
library(survey)

data(api)

# Create survey design objects ----
  #_ two-stage cluster sample: weights computed from population sizes.
    standard_design <- svydesign(ids = ~ dnum + snum, fpc = ~ fpc1 + fpc2,
                                 data = apiclus2)
  
  #_ convert to bootstrap replicate design
    boot_design <- survey::as.svrepdesign(standard_design, type = "bootstrap", replicates = 100)
#> Warning in survey::as.svrepdesign(standard_design, type = "bootstrap",
#> replicates = 100): Finite population corrections after first stage have been
#> dropped

# Ratio using srvyr ----

# Using 'base' survey method ----
  
  #_ Standard design
    svyratio(numerator = ~ api00,
             denominator = ~ api99,
             design = standard_design,
             deff = TRUE)
#> Ratio estimator: svyratio.survey.design2(numerator = ~api00, denominator = ~api99, 
#>     design = standard_design, deff = TRUE)
#> Ratios=
#>          api99
#> api00 1.039964
#> SEs=
#>             api99
#> api00 0.004620534
  
  #_ Bootstrap design with replicates
    
    #__ Works
    svyratio(numerator = ~ api00,
             denominator = ~ api99,
             design = boot_design,
             deff = FALSE)
#> Ratio estimator: svyratio.svyrep.design(numerator = ~api00, denominator = ~api99, 
#>     design = boot_design, deff = FALSE)
#> Ratios=
#>          api99
#> api00 1.039964
#> SEs=
#>             [,1]
#> [1,] 0.004758629
    
    #__ Doesn't work
    svyratio(numerator = ~ api00,
             denominator = ~ api99,
             design = boot_design,
             deff = TRUE)
#> Error in rval[i, j]: incorrect number of dimensions
```

I believe the issue is in this line of code inside `survey:::svyratio.svyrep.design()`.

https://github.com/cran/survey/blob/a0f53f8931f4e304af3c758b2ff9a56b0a2a49bd/R/surveyrep.R#L1630

Switching `rval[i,j]` to `rval$ratio[i,j]` ought to fix the problem.

@jpferreira33, you could message the author/maintainer of the `survey` package, Thomas Lumley, to suggest this bugfix.

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bschneidr** [comment]
For @jpferreira33, you'll likely find it's helpful to provide reproducible examples when you post issues on GitHub. This makes it easier for others to understand your issue and help resolve it.

Here is a nice blog post about how to provide reproducible R code for GitHub issues and other sites:
https://www.njtierney.com/post/2017/01/11/magic-reprex/
