### ISSUE TITLE
Running srvyr in a function

### ISSUE THREAD

**Issue by ABSOD** [gergness/srvyr#85]
Hi,
srvyr is a significant enhancement to survey.  Thanks for the good work.
I have a function that reads a survey data frame (in this case, generated by as_survey_rep()) and two variables to produce a contingency table.  (My task is to complete and process a few hundred tables.)  The function and the call:
`tblOutput <- function(inData,colvar,rowvar) {
    
    tdata <- inData %>%  group_by(colvar,rowvar) %>%
          summarize(percent = survey_mean(),
                 total = survey_total())
    
    return(tdata)
  }
  
  test08 <- tblOutput(f.HPS_08,"EGENDER","RSNNOWORK")`

The error message I receive is:
`Error: Must group by variables found in `.data`.
* Column `colvar` is not found.
* Column `rowvar` is not found.`

If there a way to specify the  group_by() variables in a function call?
TIA
AB

**Comment by bschneidr** [comment]
Here's a general reference for how to do what you're attempting in `dplyr` and packages that use `dplyr`.

https://dplyr.tidyverse.org/articles/programming.html

**Comment by ABSOD** [comment]
Got it.  Thanks! AB

**Comment by gergness** [comment]
Indeed, thanks @bschneidr! I've always struggled knowing where to put that in the srvyr documentation, so if you feel it's missing from somewhere in particular please let me know!

**Comment by ABSOD** [comment]
Hello Gergness/Srvyr,
Building a vignette around this capability would be a valid contribution to
your package.  In this particular context, I am generating a few hundred
tables from a longitudinal data set with 12 iterations (the Census
Household Pulse Survey).  Any examples showing how to automate the
processing of these data files, creating the survey objects, and
streamlining table production would be helpful.

...and perhaps you can get my team to stop asking for so many tables.

Cheers--
Adam Bickford
State Demography Office

On Sat, Jul 18, 2020 at 12:59 PM Greg Freedman Ellis <
notifications@github.com> wrote:

> Indeed, thanks @bschneidr
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bschneidr&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=_48y1zlosAiNKKUs9y9scnjxUfv3AM7QUTpY70d48Tw&m=F19QEqaqM8EGhkxnJwI8p1Mb0YrqlBnI8JyirDLZ2qw&s=BDc0hfTD4lRBD6yHemeCWlxJEfJ7aK12rlxMoqkmLNk&e=>!
> I've always struggled knowing where to put that in the srvyr documentation,
> so if you feel it's missing from somewhere in particular please let me know!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gergness_srvyr_issues_85-23issuecomment-2D660526291&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=_48y1zlosAiNKKUs9y9scnjxUfv3AM7QUTpY70d48Tw&m=F19QEqaqM8EGhkxnJwI8p1Mb0YrqlBnI8JyirDLZ2qw&s=Vevf29dBlAPHzMl_jJsFFIWkh61AHkjuoIRGFmjjVNI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH2T4FFIM4TY45UAFCLBDGDR4HWKFANCNFSM4OV3CORA&d=DwMCaQ&c=sdnEM9SRGFuMt5z5w3AhsPNahmNicq64TgF1JwNR0cs&r=_48y1zlosAiNKKUs9y9scnjxUfv3AM7QUTpY70d48Tw&m=F19QEqaqM8EGhkxnJwI8p1Mb0YrqlBnI8JyirDLZ2qw&s=rnwpGkXQHRmz7vOqqm0v0bJ6uKteFCrsY7ooT8XRpf0&e=>
> .
>


-- 
*Adam Bickford, Ph.D.*
*Data Analyst and Outreach Coordinator*
*Colorado State Demography Office *


P 303.864.7753 | F 303.353.0751 | 1313 Sherman St., Suite 521, Denver, CO
80203
adam.bickford@state.co.us | https://demography.dola.colorado.gov/
*Please Note:* The staff of the State Demography Office is working
remotely.
Be healthy, be smart, be safe.
*Under the Colorado Open Records Act (CORA), all messages sent by or to me
on this state-owned e-mail account may be subject to public disclosure.*

**Comment by gergness** [comment]
Ha, always good to hear srvyr's being used in state governments, it started it's life making [this report](https://idph.iowa.gov/Portals/1/userfiles/31/2013%20IA%20PRAMS%20Databook%20FINAL.pdf) for the Iowa Department of Public Health (as you might imagine, the team kept changing their minds about what questions & demographic variables they wanted to publish).

I'll keep a vignette in mind, currently struggling to keep srvyr apace with dplyr, so don't want to duplicate their programming vignette too much.
