### ISSUE TITLE
as_survey(tbl_svy) drops design information.

### ISSUE THREAD

**Issue by krivit** [gergness/srvyr#97]
This seems like odd behaviour:
```{r}
example(as_survey) # To get some tbl_svy objects, including dstrata.
dstrata # ids `1`, strata = stype, weights = pw
as_survey(dstrata) # Independent sample with replacement.
```
I would have expected the object to be returned unchanged, since it's already a `tbl_svy`. Is this intentional?

**Comment by krivit** [comment]
If it's not supposed to do this, I would be happy to submit a PR (though it should be a trivial pass-through).

**Comment by gergness** [comment]
Oh yea, that seems like a pretty clear bug, thanks!

**Comment by gergness** [comment]
The good news is I don't think it's as bad as it looks? But still please do fix.

``` r
library(survey)
library(dplyr)
library(srvyr)
library(waldo)
data(api)

dstrata <- apistrat %>%
  as_survey(strata = stype, weights = pw)

dstrata_as_survey <- dstrata %>%
  as_survey()

compare(
  dstrata_as_survey %>% summarize(x = survey_mean(api99)), 
  dstrata %>% summarize(x = survey_mean(api99))
)
#> ✓ No differences


# not the same as
nostrata <- apistrat %>%
  as_survey(weights = pw)


compare(
  dstrata %>% summarize(x = survey_mean(api99)), 
  nostrata %>% summarize(x = survey_mean(api99))
)
#> `x$x_se`: 10.10
#> `y$x_se`: 10.09
```

**Comment by krivit** [comment]
Two questions before I open a PR:

1. What to do about `as_survey_()`? On the one hand, it's deprecated and not a generic. On the other hand, its behaviour should be consistent with `as_survey()`'s.
2. Should I add myself as a contributor in the DESCRIPTION?

**Comment by krivit** [comment]
On further thought, this is probably a bigger question:

3\. What should happen when `as_survey(tbl_svy, ...)` is called with some survey arguments in `...`? Should it 1) extract the variables and recreate the `tbl_svy`, dropping the old design information, 2) update the dataset with the new design information, or 3) ignore/warn/abort.

Under approach (1), the current behaviour is actually more consistent than the proposed one, because it is a special case with no `...` arguments. Approach (2) is appealing, but it's nontrivial, needs to check for inconsistent specifications, and should probably be an `update()` method anyway. I favour approach (3), with either an error or a warning, since all the user has to do to fix it is pass the `tbl_svy` object through `as_tibble()`.

**Comment by gergness** [comment]
Going in reverse order

3) Yeah, option 3 makes sense to me. I think one could use `survey::update()` if they really wanted to change survey design on a srvyr object and it doesn't feel like a frequent enough need to justify the code complexity.

2) Yes, please add yourself as a contributor. Thank you for the help!

1) If it's not too hard, please add the same logic to `as_survey_()`
